#!/bin/sh
# This file was automatically generated on Fri 05 Jul 2024 17:42:33 BST from
# source: /dls_sw/work/R3.14.12.7/support/GIGE-BUILDER/etc/makeIocs/TEST-DI-IOC-01.xml
# 
# *** Please do not edit this file: edit the source file instead. ***
# 
cd "$(dirname "$0")"
if [ -n "$1" ]; then
    export EPICS_CA_SERVER_PORT="$(($1))"
    export EPICS_CA_REPEATER_PORT="$(($1 + 1))"
    [ $EPICS_CA_SERVER_PORT -gt 0 ] || {
        echo "First argument '$1' should be a integer greater than 0"
        exit 1
    }
fi


exec ./TEST-DI-IOC-01 stTEST-DI-IOC-01.boot
