/* This file was automatically generated on Fri 05 Jul 2024 17:42:33 BST from
 * source: /dls_sw/work/R3.14.12.7/support/GIGE-BUILDER/etc/makeIocs/TEST-DI-IOC-01.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

